/*
 * This file was generated by micropython-extmod-generator
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 forester3
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "py/nlr.h"
#include "py/obj.h"
#include "py/runtime.h"
#include "py/binary.h"
#include "portmodules.h"
#include "boards/STM32F7DISC/stm32746g_discovery_lcd.h"
#include "string.h"

extern uint8_t lcd_fb[16][RK043FN48H_WIDTH*RK043FN48H_HEIGHT*4];

extern LTDC_HandleTypeDef   hLtdcHandler;       // in stm32746g_discovery_lcd.c
extern int32_t    ActiveLayer;                  // in stm32746g_discovery_lcd.c
extern LCD_DrawPropTypeDef DrawProp[];          // in stm32746g_discovery_lcd.c

const char *format[LTDC_PIXEL_FORMAT_AL88+1] = {
            "ARGB8888", "RGB888", "RGB565", "ARGB1555", "ARGB4444", "L8", "AL44", "AL88"
};

const char *get_pix_format(void){
    return format[hLtdcHandler.LayerCfg[ActiveLayer].PixelFormat];
}

// def init()
STATIC mp_obj_t mod_lcdF7D_init(void) {
    uint8_t ret = 0;

    ret = BSP_LCD_Init();
    if(ret != 0)    mp_obj_new_int(ret);

    BSP_LCD_LayerDefaultInit(0, (uint32_t)&lcd_fb[1] );
    BSP_LCD_LayerDefaultInit(1, (uint32_t)&lcd_fb[3] );

    BSP_LCD_DisplayOn();

    BSP_LCD_SelectLayer(0);
    BSP_LCD_Clear(LCD_COLOR_BLACK);

    BSP_LCD_SelectLayer(1);
    BSP_LCD_Clear(LCD_COLOR_BLACK);

    BSP_LCD_SetFont(&LCD_DEFAULT_FONT);

    BSP_LCD_SetBackColor(LCD_COLOR_BLACK);
    BSP_LCD_SetTextColor(LCD_COLOR_WHITE);

return mp_obj_new_int(ret);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_init_obj, mod_lcdF7D_init);

// def deinit()
STATIC mp_obj_t mod_lcdF7D_deinit(void) {
    return mp_obj_new_int(BSP_LCD_DeInit());
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_deinit_obj, mod_lcdF7D_deinit);

// def get_size()
STATIC mp_obj_t mod_lcdF7D_get_size(void) {
    mp_obj_t tuple[2] = {
        mp_obj_new_int(BSP_LCD_GetXSize()),
        mp_obj_new_int(BSP_LCD_GetYSize())
    };
    return mp_obj_new_tuple(2, tuple);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_get_size_obj, mod_lcdF7D_get_size);

// def get_x_size()
STATIC mp_obj_t mod_lcdF7D_get_x_size(void) {
    return mp_obj_new_int(BSP_LCD_GetXSize());
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_get_x_size_obj, mod_lcdF7D_get_x_size);

// def get_y_size()
STATIC mp_obj_t mod_lcdF7D_get_y_size(void) {
    return mp_obj_new_int(BSP_LCD_GetYSize());
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_get_y_size_obj, mod_lcdF7D_get_y_size);

// def set_size(imageWidthPixels, imageHeightPixels)
STATIC mp_obj_t mod_lcdF7D_set_size(mp_obj_t imageWidthPixels, mp_obj_t imageHeightPixels) {
    BSP_LCD_SetXSize(mp_obj_get_int(imageWidthPixels));
    BSP_LCD_SetYSize(mp_obj_get_int(imageHeightPixels));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_set_size_obj, mod_lcdF7D_set_size);

// def set_x_size(imageWidthPixels)
STATIC mp_obj_t mod_lcdF7D_set_x_size(mp_obj_t imageWidthPixels) {
    BSP_LCD_SetXSize(mp_obj_get_int(imageWidthPixels));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_set_x_size_obj, mod_lcdF7D_set_x_size);

// def set_y_size(imageHeightPixels)
STATIC mp_obj_t mod_lcdF7D_set_y_size(mp_obj_t imageHeightPixels) {
    BSP_LCD_SetYSize(mp_obj_get_int(imageHeightPixels));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_set_y_size_obj, mod_lcdF7D_set_y_size);

// def layer_default_init(LayerIndex, FbAdress)
STATIC mp_obj_t mod_lcdF7D_layer_default_init(mp_obj_t LayerIndex) {
    int32_t     i = mp_obj_get_int(LayerIndex);
    uint32_t    fba;

    i = mp_obj_get_int(LayerIndex);
    if      ( i == 0 )  fba = (uint32_t)&lcd_fb[1];
    else if ( i == 1 )  fba = (uint32_t)&lcd_fb[3];
    else                return mp_const_none;

    BSP_LCD_LayerDefaultInit(mp_obj_get_int(LayerIndex), fba);
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_layer_default_init_obj, mod_lcdF7D_layer_default_init);

// def layer_rgb565_init(LayerIndex, FbAdress)
STATIC mp_obj_t mod_lcdF7D_layer_rgb565_init(mp_obj_t LayerIndex) {
    int32_t     i = mp_obj_get_int(LayerIndex);
    uint32_t    fba;

    i = mp_obj_get_int(LayerIndex);
    if      ( i == 0 )  fba = (uint32_t)&lcd_fb[1];
    else if ( i == 1 )  fba = (uint32_t)&lcd_fb[3];
    else                return mp_const_none;

    BSP_LCD_LayerRgb565Init(mp_obj_get_int(LayerIndex), fba);
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_layer_rgb565_init_obj, mod_lcdF7D_layer_rgb565_init);

// def select_layer(LayerIndex)
STATIC mp_obj_t mod_lcdF7D_select_layer(mp_obj_t LayerIndex) {
    BSP_LCD_SelectLayer(ActiveLayer);
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_select_layer_obj, mod_lcdF7D_select_layer);

// def set_layer_visible(LayerIndex, State)
STATIC mp_obj_t mod_lcdF7D_set_layer_visible(mp_obj_t LayerIndex, mp_obj_t State) {
    BSP_LCD_SetLayerVisible(mp_obj_get_int(LayerIndex), mp_obj_get_int(State));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_set_layer_visible_obj, mod_lcdF7D_set_layer_visible);

// def set_layer_visible_noreload(LayerIndex, State)
STATIC mp_obj_t mod_lcdF7D_set_layer_visible_noreload(mp_obj_t LayerIndex, mp_obj_t State) {
    BSP_LCD_SetLayerVisible_NoReload(mp_obj_get_int(LayerIndex), mp_obj_get_int(State));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_set_layer_visible_noreload_obj, mod_lcdF7D_set_layer_visible_noreload);

// def set_transparency(LayerIndex, Transparency)
STATIC mp_obj_t mod_lcdF7D_set_transparency(mp_obj_t LayerIndex, mp_obj_t Transparency) {
    BSP_LCD_SetTransparency(mp_obj_get_int(LayerIndex), mp_obj_get_int(Transparency));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_set_transparency_obj, mod_lcdF7D_set_transparency);

// def set_transparency_noreload(LayerIndex, Transparency)
STATIC mp_obj_t mod_lcdF7D_set_transparency_noreload(mp_obj_t LayerIndex, mp_obj_t Transparency) {
    BSP_LCD_SetTransparency_NoReload(mp_obj_get_int(LayerIndex), mp_obj_get_int(Transparency));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_set_transparency_noreload_obj, mod_lcdF7D_set_transparency_noreload);

// def set_layer_address(LayerIndex, Address)
STATIC mp_obj_t mod_lcdF7D_set_layer_address(mp_obj_t LayerIndex, mp_obj_t Address) {
    BSP_LCD_SetLayerAddress(mp_obj_get_int(LayerIndex), (uint32_t)0xC0000000 );
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_set_layer_address_obj, mod_lcdF7D_set_layer_address);

// def set_layer_address_noreload(LayerIndex, Address)
STATIC mp_obj_t mod_lcdF7D_set_layer_address_noreload(mp_obj_t LayerIndex, mp_obj_t Address) {
    BSP_LCD_SetLayerAddress_NoReload(mp_obj_get_int(LayerIndex),
                                        (uint32_t)MP_OBJ_TO_PTR(Address));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_set_layer_address_noreload_obj, mod_lcdF7D_set_layer_address_noreload);

// def set_layer_window(LayerIndex, Xpos, Ypos, Width, Height)
STATIC mp_obj_t mod_lcdF7D_set_layer_window(size_t n_args, const mp_obj_t *args) {
    BSP_LCD_SetLayerWindow( mp_obj_get_int(args[0]), mp_obj_get_int(args[1]),
                            mp_obj_get_int(args[2]), mp_obj_get_int(args[3]),
                            mp_obj_get_int(args[4]));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_set_layer_window_obj, 5, 5, mod_lcdF7D_set_layer_window);

// def set_layer_window_noreload(LayerIndex, Xpos, Ypos, Width, Height)
STATIC mp_obj_t mod_lcdF7D_set_layer_window_noreload(size_t n_args, const mp_obj_t *args) {
    BSP_LCD_SetLayerWindow_NoReload( mp_obj_get_int(args[0]), mp_obj_get_int(args[1]),
                                    mp_obj_get_int(args[2]), mp_obj_get_int(args[3]),
                                    mp_obj_get_int(args[4]) );
     return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_set_layer_window_noreload_obj, 5, 5, mod_lcdF7D_set_layer_window_noreload);

// def set_color_keying(LayerIndex, RGBValue->r,g,b)
STATIC mp_obj_t mod_lcdF7D_set_color_keying(size_t n_args, const mp_obj_t *args) {
    uint32_t    rgb;

    rgb = ((mp_obj_get_int(args[1]) & 0xFF) << 16)
            + ((mp_obj_get_int(args[2]) & 0xFF) << 8 )
            +  (mp_obj_get_int(args[3]) & 0xFF);

    BSP_LCD_SetColorKeying( mp_obj_get_int(args[0]), rgb );
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_set_color_keying_obj, 4, 4, mod_lcdF7D_set_color_keying);

// def set_color_keying_noreload(LayerIndes, RGBValue->r,g,b)
STATIC mp_obj_t mod_lcdF7D_set_color_keying_noreload(size_t n_args, const mp_obj_t *args) {
    uint32_t    rgb;

    rgb = ((mp_obj_get_int(args[1]) & 0xFF) << 16)
            + ((mp_obj_get_int(args[2]) & 0xFF) << 8 )
            +  (mp_obj_get_int(args[3]) & 0xFF);

    BSP_LCD_SetColorKeying_NoReload( mp_obj_get_int(args[0]), rgb );
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_set_color_keying_noreload_obj, 4, 4, mod_lcdF7D_set_color_keying_noreload);

// def reset_color_keying(LayerIndex)
STATIC mp_obj_t mod_lcdF7D_reset_color_keying(mp_obj_t LayerIndex) {
    BSP_LCD_ResetColorKeying( mp_obj_get_int(LayerIndex) );
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_reset_color_keying_obj, mod_lcdF7D_reset_color_keying);

// def reset_color_keying_noreload(LayerIndex)
STATIC mp_obj_t mod_lcdF7D_reset_color_keying_noreload(mp_obj_t LayerIndex) {
    BSP_LCD_ResetColorKeying_NoReload( mp_obj_get_int(LayerIndex) );
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_reset_color_keying_noreload_obj, mod_lcdF7D_reset_color_keying_noreload);

// def reload(ReloadType)
STATIC mp_obj_t mod_lcdF7D_reload(mp_obj_t ReloadType) {
    BSP_LCD_Reload( mp_obj_get_int(ReloadType) );
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_reload_obj, mod_lcdF7D_reload);

// def set_text_color(Color->a,r,g,b)
STATIC mp_obj_t mod_lcdF7D_set_text_color(size_t n_args, const mp_obj_t *args) {
    uint32_t    argb;

    argb = (((uint32_t)mp_obj_get_int(args[0]) & 0xFF) << 24)
            + ((mp_obj_get_int(args[1]) & 0xFF) << 16)
            + ((mp_obj_get_int(args[2]) & 0xFF) << 8 )
            +  (mp_obj_get_int(args[3]) & 0xFF);

    BSP_LCD_SetTextColor(argb);
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_set_text_color_obj, 4, 4, mod_lcdF7D_set_text_color);

// def get_text_color()
STATIC mp_obj_t mod_lcdF7D_get_text_color(void) {
    uint32_t    argb;
    uint8_t     a, r ,g, b;

    argb = BSP_LCD_GetTextColor();
    a = (argb & 0xFF000000) >> 24;
    r = (argb & 0x00FF0000) >> 16;
    g = (argb & 0x0000FF00) >> 8;
    b =  argb & 0x000000FF;
    mp_obj_t tuple[4] = {
        mp_obj_new_int(a), mp_obj_new_int(r), mp_obj_new_int(g), mp_obj_new_int(b)
    };
    return mp_obj_new_tuple(4, tuple);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_get_text_color_obj, mod_lcdF7D_get_text_color);

// def set_back_color(Color->a,r,g,b)
STATIC mp_obj_t mod_lcdF7D_set_back_color(size_t n_args, const mp_obj_t *args) {
    uint32_t    argb;

    argb = (((uint32_t)mp_obj_get_int(args[0]) & 0xFF) << 24)
            + ((mp_obj_get_int(args[1]) & 0xFF) << 16)
            + ((mp_obj_get_int(args[2]) & 0xFF) << 8 )
            +  (mp_obj_get_int(args[3]) & 0xFF);

    BSP_LCD_SetBackColor(argb);
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_set_back_color_obj, 4, 4, mod_lcdF7D_set_back_color);

// def get_back_color()
STATIC mp_obj_t mod_lcdF7D_get_back_color(void) {
    uint32_t    argb;
    uint8_t     a, r, g, b;

    argb = DrawProp[ActiveLayer].BackColor;
    a = (argb & 0xFF000000) >> 24;
    r = (argb & 0x00FF0000) >> 16;
    g = (argb & 0x0000FF00) >> 8;
    b =  argb & 0x000000FF;
    mp_obj_t tuple[4] = {
        mp_obj_new_int(a), mp_obj_new_int(r), mp_obj_new_int(g), mp_obj_new_int(b)
    };
    return mp_obj_new_tuple(4, tuple);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_get_back_color_obj, mod_lcdF7D_get_back_color);

// def set_font(pFonts)
STATIC mp_obj_t mod_lcdF7D_set_font(mp_obj_t size) {

    int32_t  s = mp_obj_get_int(size);
    void    *p = &Font24;

    if      ( s <= 8 )   p = &Font8;
    else if( s <= 12 )   p = &Font12;
    else if( s <= 16 )   p = &Font16;
    else if( s <= 20 )   p = &Font20;

    BSP_LCD_SetFont(p);
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_set_font_obj, mod_lcdF7D_set_font);

// def get_font()
STATIC mp_obj_t mod_lcdF7D_get_font(void) {

    int32_t size = -1;
    void    *p;

    p = BSP_LCD_GetFont();

    if     ( p == &Font8  ) size =  8;
    else if( p == &Font12 ) size = 12;
    else if( p == &Font16 ) size = 16;
    else if( p == &Font20 ) size = 20;
    else if( p == &Font24 ) size = 24;

    return mp_obj_new_int(size);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_get_font_obj, mod_lcdF7D_get_font);

// def read_pixel(Xpos, Ypos)
STATIC mp_obj_t mod_lcdF7D_read_pixel(mp_obj_t Xpos, mp_obj_t Ypos) {
    const char *pix_format;
    uint8_t a=0, r=0, g=0, b=0;
    uint32_t argb;

    argb = BSP_LCD_ReadPixel(mp_obj_get_int(Xpos), mp_obj_get_int(Ypos));
    pix_format = get_pix_format();

    if(hLtdcHandler.LayerCfg[ActiveLayer].PixelFormat == LTDC_PIXEL_FORMAT_ARGB8888){
        a = (argb & 0xFF000000) >> 24;
        r = (argb & 0x00FF0000) >> 16;
        g = (argb & 0x0000FF00) >> 8;
        b =  argb & 0x000000FF;
    }
    else if(hLtdcHandler.LayerCfg[ActiveLayer].PixelFormat == LTDC_PIXEL_FORMAT_RGB888){
        r = (argb & 0x00FF0000) >> 16;
        g = (argb & 0x0000FF00) >> 8;
        b =  argb & 0x000000FF;
    }
    else if(hLtdcHandler.LayerCfg[ActiveLayer].PixelFormat == LTDC_PIXEL_FORMAT_RGB565){
        r = (argb & 0x0000F800) >> 11;
        g = (argb & 0x000007E0) >> 5;
        b =  argb & 0x0000001F;
    }

    mp_obj_t tuple[5] = {
        mp_obj_new_str(pix_format, strlen(pix_format)), mp_obj_new_int(a),
        mp_obj_new_int(r), mp_obj_new_int(g), mp_obj_new_int(b)
    };

    return mp_obj_new_tuple(5, tuple);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_read_pixel_obj, mod_lcdF7D_read_pixel);


// def clear(Color->a,r,g,b)
STATIC mp_obj_t mod_lcdF7D_clear(size_t n_args, const mp_obj_t *args) {
    uint32_t Color;
    Color = (mp_obj_get_int(args[0]) << 24) + (mp_obj_get_int(args[1]) << 16)
            + (mp_obj_get_int(args[2]) << 8) + mp_obj_get_int(args[3]);
    BSP_LCD_Clear(Color);

    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_clear_obj, 4, 4, mod_lcdF7D_clear);

// def clear_string_line(Line)
STATIC mp_obj_t mod_lcdF7D_clear_string_line(mp_obj_t Line) {
    BSP_LCD_ClearStringLine(mp_obj_get_int(Line));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_lcdF7D_clear_string_line_obj, mod_lcdF7D_clear_string_line);

// def display_char(Xpos, Ypos, Ascii)
STATIC mp_obj_t mod_lcdF7D_display_char(mp_obj_t Xpos, mp_obj_t Ypos, mp_obj_t Ascii) {
    BSP_LCD_DisplayChar(mp_obj_get_int(Xpos), mp_obj_get_int(Ypos), mp_obj_get_int(Ascii));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_3(mod_lcdF7D_display_char_obj, mod_lcdF7D_display_char);

// def display_string_at(Xpos, Ypos, pText, Mode)
STATIC mp_obj_t mod_lcdF7D_display_string_at(size_t n_args, const mp_obj_t *args) {
    BSP_LCD_DisplayStringAt(mp_obj_get_int(args[0]), mp_obj_get_int(args[1]),
                            (uint8_t *)mp_obj_str_get_str(args[2]), mp_obj_get_int(args[3]));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_display_string_at_obj, 4, 4, mod_lcdF7D_display_string_at);

// def display_string_at_line(Line, pText)
STATIC mp_obj_t mod_lcdF7D_display_string_at_line(mp_obj_t Line, mp_obj_t pText ) {
    BSP_LCD_DisplayStringAtLine(mp_obj_get_int(Line), (uint8_t *)mp_obj_str_get_str(pText));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_display_string_at_line_obj, mod_lcdF7D_display_string_at_line);

// def draw_Hline(Xpos, Ypos, Length)
STATIC mp_obj_t mod_lcdF7D_draw_Hline(mp_obj_t Xpos, mp_obj_t Ypos, mp_obj_t Length) {
    BSP_LCD_DrawHLine(mp_obj_get_int(Xpos), mp_obj_get_int(Ypos), mp_obj_get_int(Length));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_3(mod_lcdF7D_draw_Hline_obj, mod_lcdF7D_draw_Hline);

// def draw_Vline(Xpos, Ypos, Length)
STATIC mp_obj_t mod_lcdF7D_draw_Vline(mp_obj_t Xpos, mp_obj_t Ypos, mp_obj_t Length) {
    BSP_LCD_DrawVLine(mp_obj_get_int(Xpos), mp_obj_get_int(Ypos), mp_obj_get_int(Length));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_3(mod_lcdF7D_draw_Vline_obj, mod_lcdF7D_draw_Vline);

// def draw_line(x1, y1, x2, y2)
STATIC mp_obj_t mod_lcdF7D_draw_line(size_t n_args, const mp_obj_t *args) {
    BSP_LCD_DrawLine(mp_obj_get_int(args[0]), mp_obj_get_int(args[1]),
                    mp_obj_get_int(args[2]), mp_obj_get_int(args[3]));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_draw_line_obj, 4, 4, mod_lcdF7D_draw_line);

// def draw_rect(Xpos, Ypos, Width, Height)
STATIC mp_obj_t mod_lcdF7D_draw_rect(size_t n_args, const mp_obj_t *args) {
    BSP_LCD_DrawRect(mp_obj_get_int(args[0]), mp_obj_get_int(args[1]),
                    mp_obj_get_int(args[2]), mp_obj_get_int(args[3]));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_draw_rect_obj, 4, 4, mod_lcdF7D_draw_rect);

// def draw_circle(Xpos, Ypos, Radius)
STATIC mp_obj_t mod_lcdF7D_draw_circle(mp_obj_t Xpos, mp_obj_t Ypos, mp_obj_t Radius) {
    BSP_LCD_DrawCircle(mp_obj_get_int(Xpos), mp_obj_get_int(Ypos), mp_obj_get_int(Radius));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_3(mod_lcdF7D_draw_circle_obj, mod_lcdF7D_draw_circle);

// def draw_polygon(Points, PointCount)
STATIC mp_obj_t mod_lcdF7D_draw_polygon(mp_obj_t Points, mp_obj_t PointCount) {
    BSP_LCD_DrawPolygon( MP_OBJ_TO_PTR(Points), (uint16_t)mp_obj_get_int(PointCount) );
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_draw_polygon_obj, mod_lcdF7D_draw_polygon);

// def draw_ellipse(Xpos, Ypos, XRadius, YRadius)
STATIC mp_obj_t mod_lcdF7D_draw_ellipse(size_t n_args, const mp_obj_t *args) {
    BSP_LCD_DrawEllipse(mp_obj_get_int(args[0]), mp_obj_get_int(args[1]),
                         mp_obj_get_int(args[2]), mp_obj_get_int(args[3]));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_draw_ellipse_obj, 4, 4, mod_lcdF7D_draw_ellipse);

// def draw_pixel(Xpos, Ypos, RGB_Code)
STATIC mp_obj_t mod_lcdF7D_draw_pixel(size_t n_args, const mp_obj_t *args) {
    uint32_t argb;

    if(hLtdcHandler.LayerCfg[ActiveLayer].PixelFormat == LTDC_PIXEL_FORMAT_RGB565){
            /* RGB565 format */
        argb = ((mp_obj_get_int(args[3]) & 0x1F) << 11)
                + ((mp_obj_get_int(args[4]) & 0x3F) << 5)
                + (mp_obj_get_int(args[5]) & 0x1F);
    }
    else{   /* ARGB8888 format */
        argb = ((uint32_t)(mp_obj_get_int(args[2]) & 0xFF) << 24)
                + ((mp_obj_get_int(args[3]) & 0xFF) << 16)
                + ((mp_obj_get_int(args[4]) & 0xFF) << 8)
                +  (mp_obj_get_int(args[5]) & 0xFF);
    }

    BSP_LCD_DrawPixel(mp_obj_get_int(args[0]), mp_obj_get_int(args[1]), argb);
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_draw_pixel_obj, 6, 6, mod_lcdF7D_draw_pixel);

// def draw_bitmap(Xpos, Ypos, pBmp)
STATIC mp_obj_t mod_lcdF7D_draw_bitmap(mp_obj_t Xpos, mp_obj_t Ypos, mp_obj_t pBmp) {
    BSP_LCD_DrawBitmap(mp_obj_get_int(Xpos), mp_obj_get_int(Ypos), pBmp);
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_3(mod_lcdF7D_draw_bitmap_obj, mod_lcdF7D_draw_bitmap);

// def fill_rect(Xpos, Ypos, Width, Height)
STATIC mp_obj_t mod_lcdF7D_fill_rect(size_t n_args, const mp_obj_t *args) {
    BSP_LCD_FillRect(mp_obj_get_int(args[0]), mp_obj_get_int(args[1]),
                    mp_obj_get_int(args[2]), mp_obj_get_int(args[3]));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_fill_rect_obj, 4, 4, mod_lcdF7D_fill_rect);

// def fill_circle(Xpos, Ypos, Radius)
STATIC mp_obj_t mod_lcdF7D_fill_circle(mp_obj_t Xpos, mp_obj_t Ypos, mp_obj_t Radius) {
    BSP_LCD_FillCircle(mp_obj_get_int(Xpos), mp_obj_get_int(Ypos), mp_obj_get_int(Radius));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_3(mod_lcdF7D_fill_circle_obj, mod_lcdF7D_fill_circle);

// def fill_polygon(Points, PointCount)
STATIC mp_obj_t mod_lcdF7D_fill_polygon(mp_obj_t Points, mp_obj_t PointCount) {
    BSP_LCD_FillPolygon(MP_OBJ_TO_PTR(Points), (uint16_t)mp_obj_get_int(PointCount));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_lcdF7D_fill_polygon_obj, mod_lcdF7D_fill_polygon);

// def fill_ellipse(Xpos, Ypos, XRadius, YRadius)
STATIC mp_obj_t mod_lcdF7D_fill_ellipse(size_t n_args, const mp_obj_t *args) {
    BSP_LCD_FillEllipse(mp_obj_get_int(args[0]), mp_obj_get_int(args[1]),
                        mp_obj_get_int(args[2]), mp_obj_get_int(args[3]));
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(mod_lcdF7D_fill_ellipse_obj, 4, 4, mod_lcdF7D_fill_ellipse);

// def display_on()
STATIC mp_obj_t mod_lcdF7D_display_on(void) {
    BSP_LCD_DisplayOn();
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_display_on_obj, mod_lcdF7D_display_on);

// def display_off()
STATIC mp_obj_t mod_lcdF7D_display_off(void) {
    BSP_LCD_DisplayOff();
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_lcdF7D_display_off_obj, mod_lcdF7D_display_off);

// module stuff

STATIC const mp_rom_map_elem_t mp_module_lcdF7D_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_lcdF7D) },
    { MP_ROM_QSTR(MP_QSTR_clear), MP_ROM_PTR(&mod_lcdF7D_clear_obj) },
    { MP_ROM_QSTR(MP_QSTR_clear_string_line), MP_ROM_PTR(&mod_lcdF7D_clear_string_line_obj) },
//    { MP_ROM_QSTR(MP_QSTR_clock_config), MP_ROM_PTR(&mod_lcdF7D_clock_config_obj) },
//    { MP_ROM_QSTR(MP_QSTR_convert_line_to_ARGB8888), MP_ROM_PTR(&mod_lcdF7D_convert_line_to_ARGB8888_obj) },
    { MP_ROM_QSTR(MP_QSTR_deinit), MP_ROM_PTR(&mod_lcdF7D_deinit_obj) },
    { MP_ROM_QSTR(MP_QSTR_display_char), MP_ROM_PTR(&mod_lcdF7D_display_char_obj) },
    { MP_ROM_QSTR(MP_QSTR_display_off), MP_ROM_PTR(&mod_lcdF7D_display_off_obj) },
    { MP_ROM_QSTR(MP_QSTR_display_on), MP_ROM_PTR(&mod_lcdF7D_display_on_obj) },
    { MP_ROM_QSTR(MP_QSTR_display_string_at), MP_ROM_PTR(&mod_lcdF7D_display_string_at_obj) },
    { MP_ROM_QSTR(MP_QSTR_display_string_at_line), MP_ROM_PTR(&mod_lcdF7D_display_string_at_line_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_Hline), MP_ROM_PTR(&mod_lcdF7D_draw_Hline_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_Vline), MP_ROM_PTR(&mod_lcdF7D_draw_Vline_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_bitmap), MP_ROM_PTR(&mod_lcdF7D_draw_bitmap_obj) },
//    { MP_ROM_QSTR(MP_QSTR_draw_char), MP_ROM_PTR(&mod_lcdF7D_draw_char_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_circle), MP_ROM_PTR(&mod_lcdF7D_draw_circle_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_ellipse), MP_ROM_PTR(&mod_lcdF7D_draw_ellipse_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_line), MP_ROM_PTR(&mod_lcdF7D_draw_line_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_pixel), MP_ROM_PTR(&mod_lcdF7D_draw_pixel_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_polygon), MP_ROM_PTR(&mod_lcdF7D_draw_polygon_obj) },
    { MP_ROM_QSTR(MP_QSTR_draw_rect), MP_ROM_PTR(&mod_lcdF7D_draw_rect_obj) },
//    { MP_ROM_QSTR(MP_QSTR_fill_buffer), MP_ROM_PTR(&mod_lcdF7D_fill_buffer_obj) },
    { MP_ROM_QSTR(MP_QSTR_fill_circle), MP_ROM_PTR(&mod_lcdF7D_fill_circle_obj) },
    { MP_ROM_QSTR(MP_QSTR_fill_ellipse), MP_ROM_PTR(&mod_lcdF7D_fill_ellipse_obj) },
    { MP_ROM_QSTR(MP_QSTR_fill_polygon), MP_ROM_PTR(&mod_lcdF7D_fill_polygon_obj) },
    { MP_ROM_QSTR(MP_QSTR_fill_rect), MP_ROM_PTR(&mod_lcdF7D_fill_rect_obj) },
//    { MP_ROM_QSTR(MP_QSTR_fill_triangle), MP_ROM_PTR(&mod_lcdF7D_fill_triangle_obj) },
    { MP_ROM_QSTR(MP_QSTR_get_back_color), MP_ROM_PTR(&mod_lcdF7D_get_back_color_obj) },
    { MP_ROM_QSTR(MP_QSTR_get_font), MP_ROM_PTR(&mod_lcdF7D_get_font_obj) },
    { MP_ROM_QSTR(MP_QSTR_get_size), MP_ROM_PTR(&mod_lcdF7D_get_size_obj) },
    { MP_ROM_QSTR(MP_QSTR_get_text_color), MP_ROM_PTR(&mod_lcdF7D_get_text_color_obj) },
    { MP_ROM_QSTR(MP_QSTR_get_x_size), MP_ROM_PTR(&mod_lcdF7D_get_x_size_obj) },
    { MP_ROM_QSTR(MP_QSTR_get_y_size), MP_ROM_PTR(&mod_lcdF7D_get_y_size_obj) },
    { MP_ROM_QSTR(MP_QSTR_init), MP_ROM_PTR(&mod_lcdF7D_init_obj) },
    { MP_ROM_QSTR(MP_QSTR_layer_default_init), MP_ROM_PTR(&mod_lcdF7D_layer_default_init_obj) },
    { MP_ROM_QSTR(MP_QSTR_layer_rgb565_init), MP_ROM_PTR(&mod_lcdF7D_layer_rgb565_init_obj) },
    { MP_ROM_QSTR(MP_QSTR_read_pixel), MP_ROM_PTR(&mod_lcdF7D_read_pixel_obj) },
    { MP_ROM_QSTR(MP_QSTR_reload), MP_ROM_PTR(&mod_lcdF7D_reload_obj) },
    { MP_ROM_QSTR(MP_QSTR_reset_color_keying), MP_ROM_PTR(&mod_lcdF7D_reset_color_keying_obj) },
    { MP_ROM_QSTR(MP_QSTR_reset_color_keying_noreload), MP_ROM_PTR(&mod_lcdF7D_reset_color_keying_noreload_obj) },
    { MP_ROM_QSTR(MP_QSTR_select_layer), MP_ROM_PTR(&mod_lcdF7D_select_layer_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_back_color), MP_ROM_PTR(&mod_lcdF7D_set_back_color_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_color_keying), MP_ROM_PTR(&mod_lcdF7D_set_color_keying_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_color_keying_noreload), MP_ROM_PTR(&mod_lcdF7D_set_color_keying_noreload_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_font), MP_ROM_PTR(&mod_lcdF7D_set_font_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_layer_visible_noreload), MP_ROM_PTR(&mod_lcdF7D_set_layer_visible_noreload_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_layer_address), MP_ROM_PTR(&mod_lcdF7D_set_layer_address_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_layer_address_noreload), MP_ROM_PTR(&mod_lcdF7D_set_layer_address_noreload_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_layer_visible), MP_ROM_PTR(&mod_lcdF7D_set_layer_visible_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_layer_window), MP_ROM_PTR(&mod_lcdF7D_set_layer_window_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_layer_window_noreload), MP_ROM_PTR(&mod_lcdF7D_set_layer_window_noreload_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_size), MP_ROM_PTR(&mod_lcdF7D_set_size_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_text_color), MP_ROM_PTR(&mod_lcdF7D_set_text_color_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_transparency), MP_ROM_PTR(&mod_lcdF7D_set_transparency_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_transparency_noreload), MP_ROM_PTR(&mod_lcdF7D_set_transparency_noreload_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_x_size), MP_ROM_PTR(&mod_lcdF7D_set_x_size_obj) },
    { MP_ROM_QSTR(MP_QSTR_set_y_size), MP_ROM_PTR(&mod_lcdF7D_set_y_size_obj) },
};
STATIC MP_DEFINE_CONST_DICT(mp_module_lcdF7D_globals, mp_module_lcdF7D_globals_table);

const mp_obj_module_t mp_module_lcdF7D = {
    .base = { &mp_type_module },
//    .name = MP_QSTR_lcdF7D,
    .globals = (mp_obj_dict_t*)&mp_module_lcdF7D_globals,
};

