/*
 * This file was generated by micropython-extmod-generator
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 forester3
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "py/nlr.h"
#include "py/obj.h"
#include "py/runtime.h"
#include "py/binary.h"
#include "portmodules.h"
#include "boards/STM32F7DISC/stm32746g_discovery_ts.h"

TS_StateTypeDef touchState;

// def init(size_x, size_y) -> int
STATIC mp_obj_t mod_tchF7D_init(mp_obj_t size_x, mp_obj_t size_y) {
    uint8_t ret = BSP_TS_Init(mp_obj_get_int(size_x), mp_obj_get_int(size_y));    
    return mp_obj_new_int(ret);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(mod_tchF7D_init_obj, mod_tchF7D_init);

// def deinit() -> int
STATIC mp_obj_t mod_tchF7D_deinit(void) {
        return mp_obj_new_int(BSP_TS_DeInit());
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_tchF7D_deinit_obj, mod_tchF7D_deinit);

// def get_state(state) -> int
STATIC mp_obj_t mod_tchF7D_get_state(void) {
    return mp_obj_new_int(BSP_TS_GetState(&touchState));
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_tchF7D_get_state_obj, mod_tchF7D_get_state);

// def get_gesture_id(state) -> int
STATIC mp_obj_t mod_tchF7D_get_gesture_id(void) {
    return mp_obj_new_int(BSP_TS_Get_GestureId(&touchState));
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_tchF7D_get_gesture_id_obj, mod_tchF7D_get_gesture_id);

// def reset_touch_data(state) -> int
STATIC mp_obj_t mod_tchF7D_reset_touch_data(mp_obj_t state) {
    void *tchState = MP_OBJ_TO_PTR(state);
    return mp_obj_new_int(BSP_TS_ResetTouchData(tchState));
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_tchF7D_reset_touch_data_obj, mod_tchF7D_reset_touch_data);

//
//  forester3's methods to read TS_StateTypeDef members
//

STATIC mp_obj_t mod_tchF7D_gesture(void) {
        return mp_obj_new_int(touchState.gestureId);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_tchF7D_gesture_obj, mod_tchF7D_gesture);

STATIC mp_obj_t mod_tchF7D_point_info(mp_obj_t num) {

    uint8_t n = mp_obj_get_int(num);
    if( (touchState.touchDetected < n)||(n <= 0)||(n > 5) )
    {
        mp_raise_ValueError("tchF7D.point_info(n):");
        printf("%d is out of touches !!", n);
    }
    n--;
    mp_obj_t tuple[5] = {
        mp_obj_new_int(touchState.touchX[n]), mp_obj_new_int(touchState.touchY[n]),
        mp_obj_new_int(touchState.touchWeight[n]), mp_obj_new_int(touchState.touchEventId[n]),
        mp_obj_new_int(touchState.touchArea[n])
    };   
    return mp_obj_new_tuple(5, tuple);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_tchF7D_point_info_obj, mod_tchF7D_point_info);

STATIC mp_obj_t mod_tchF7D_touches(void) {
        return mp_obj_new_int(touchState.touchDetected);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_tchF7D_touches_obj, mod_tchF7D_touches);

// module stuff

STATIC const mp_rom_map_elem_t mp_module_tchF7D_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_tchF7D) },
    { MP_ROM_QSTR(MP_QSTR_deinit), MP_ROM_PTR(&mod_tchF7D_deinit_obj) },
    { MP_ROM_QSTR(MP_QSTR_gesture), MP_ROM_PTR(&mod_tchF7D_gesture_obj) },     
    { MP_ROM_QSTR(MP_QSTR_get_gesture_id), MP_ROM_PTR(&mod_tchF7D_get_gesture_id_obj) },
    { MP_ROM_QSTR(MP_QSTR_get_state), MP_ROM_PTR(&mod_tchF7D_get_state_obj) },
    { MP_ROM_QSTR(MP_QSTR_init), MP_ROM_PTR(&mod_tchF7D_init_obj) },
    { MP_ROM_QSTR(MP_QSTR_point_info), MP_ROM_PTR(&mod_tchF7D_point_info_obj) },
    { MP_ROM_QSTR(MP_QSTR_reset_touch_data), MP_ROM_PTR(&mod_tchF7D_reset_touch_data_obj) },
    { MP_ROM_QSTR(MP_QSTR_touches), MP_ROM_PTR(&mod_tchF7D_touches_obj) },
};
STATIC MP_DEFINE_CONST_DICT(mp_module_tchF7D_globals, mp_module_tchF7D_globals_table);

const mp_obj_module_t mp_module_tchF7D = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&mp_module_tchF7D_globals,
};

